mongodb_client:
    MONGO_DB_HOST : 'localhost'
    MONGO_DB_PORT : '27017'
    DB_NAME : 'popular_news'

news_api_client:
    NEWS_API_ENDPOINT : 'https://newsapi.org/v1/'
    NEWS_API_KEY : '1c5132ec2e9f4646b62d89ac92e32903'
    ARTICLES_API : 'articles' 
    SORT_BY_TOP : 'top'
    DEFAULT_SOURCES : 
        - 'bbc-news'
        - 'cnn'
        - 'abc-news-au'
        - 'bbc-sport'
        - 'the-washington-post'
        - 'time'
        - 'usa-today'

news_recommendation_service_client:
    URL : 'http://localhost:5050/'

news_topic_modeling_service_client:
    URL : 'http://localhost:6060/'